#!/bin/bash

compile clang-intel; cp xsum-time xsum-time-clang
compile gcc-intel; cp xsum-time xsum-time-gcc

cp xsum.c xsum.c-opt
ed xsum.c <no-opt-script

compile clang-intel; cp xsum-time xsum-time-clang-no-opt
compile gcc-intel; cp xsum-time xsum-time-gcc-no-opt

cp xsum.c-opt xsum.c
rm xsum.c-opt
